// Generated by Supabase (generate_typescript_types). Regenerate after every migration; do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      activity_log: {
        Row: {
          action: string
          actor_id: string | null
          actor_label: string
          changes: Json
          created_at: string
          customer_id: string | null
          entity_id: string
          entity_type: string
          id: number
        }
        Insert: {
          action: string
          actor_id?: string | null
          actor_label: string
          changes?: Json
          created_at?: string
          customer_id?: string | null
          entity_id: string
          entity_type: string
          id?: never
        }
        Update: {
          action?: string
          actor_id?: string | null
          actor_label?: string
          changes?: Json
          created_at?: string
          customer_id?: string | null
          entity_id?: string
          entity_type?: string
          id?: never
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "staff"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_overview"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      appointments: {
        Row: {
          cancel_reason: Database["public"]["Enums"]["cancel_reason"] | null
          created_at: string
          created_by: string | null
          customer_id: string
          duration_minutes: number
          id: string
          notes: string | null
          staff_id: string | null
          starts_at: string
          status: Database["public"]["Enums"]["appointment_status"]
          treatment_id: number
          updated_at: string
        }
        Insert: {
          cancel_reason?: Database["public"]["Enums"]["cancel_reason"] | null
          created_at?: string
          created_by?: string | null
          customer_id: string
          duration_minutes: number
          id?: string
          notes?: string | null
          staff_id?: string | null
          starts_at: string
          status?: Database["public"]["Enums"]["appointment_status"]
          treatment_id: number
          updated_at?: string
        }
        Update: {
          cancel_reason?: Database["public"]["Enums"]["cancel_reason"] | null
          created_at?: string
          created_by?: string | null
          customer_id?: string
          duration_minutes?: number
          id?: string
          notes?: string | null
          staff_id?: string | null
          starts_at?: string
          status?: Database["public"]["Enums"]["appointment_status"]
          treatment_id?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "staff"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_overview"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_staff_id_fkey"
            columns: ["staff_id"]
            isOneToOne: false
            referencedRelation: "staff"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_treatment_id_fkey"
            columns: ["treatment_id"]
            isOneToOne: false
            referencedRelation: "treatments"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          created_at: string
          created_by: string | null
          email: string | null
          full_name: string
          id: string
          marketing_consent: boolean
          notes: string | null
          phone: string
          source: Database["public"]["Enums"]["customer_source"] | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          email?: string | null
          full_name: string
          id?: string
          marketing_consent?: boolean
          notes?: string | null
          phone: string
          source?: Database["public"]["Enums"]["customer_source"] | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          email?: string | null
          full_name?: string
          id?: string
          marketing_consent?: boolean
          notes?: string | null
          phone?: string
          source?: Database["public"]["Enums"]["customer_source"] | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "staff"
            referencedColumns: ["id"]
          },
        ]
      }
      integration_incidents: {
        Row: {
          created_at: string
          details: Json
          id: number
          message: string
          node: string | null
          source: string
        }
        Insert: {
          created_at?: string
          details?: Json
          id?: never
          message: string
          node?: string | null
          source: string
        }
        Update: {
          created_at?: string
          details?: Json
          id?: never
          message?: string
          node?: string | null
          source?: string
        }
        Relationships: []
      }
      staff: {
        Row: {
          created_at: string
          email: string
          full_name: string
          id: string
          is_active: boolean
          role: Database["public"]["Enums"]["staff_role"]
          specialty: string | null
        }
        Insert: {
          created_at?: string
          email: string
          full_name: string
          id: string
          is_active?: boolean
          role?: Database["public"]["Enums"]["staff_role"]
          specialty?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          is_active?: boolean
          role?: Database["public"]["Enums"]["staff_role"]
          specialty?: string | null
        }
        Relationships: []
      }
      tickets: {
        Row: {
          assignee_id: string | null
          closed_at: string | null
          created_at: string
          created_by: string | null
          customer_id: string
          description: string
          id: string
          priority: Database["public"]["Enums"]["ticket_priority"]
          reported_name: string | null
          source: Database["public"]["Enums"]["ticket_source"] | null
          status: Database["public"]["Enums"]["ticket_status"]
          subject: string | null
          ticket_number: number
          updated_at: string
        }
        Insert: {
          assignee_id?: string | null
          closed_at?: string | null
          created_at?: string
          created_by?: string | null
          customer_id: string
          description: string
          id?: string
          priority?: Database["public"]["Enums"]["ticket_priority"]
          reported_name?: string | null
          source?: Database["public"]["Enums"]["ticket_source"] | null
          status?: Database["public"]["Enums"]["ticket_status"]
          subject?: string | null
          ticket_number?: number
          updated_at?: string
        }
        Update: {
          assignee_id?: string | null
          closed_at?: string | null
          created_at?: string
          created_by?: string | null
          customer_id?: string
          description?: string
          id?: string
          priority?: Database["public"]["Enums"]["ticket_priority"]
          reported_name?: string | null
          source?: Database["public"]["Enums"]["ticket_source"] | null
          status?: Database["public"]["Enums"]["ticket_status"]
          subject?: string | null
          ticket_number?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tickets_assignee_id_fkey"
            columns: ["assignee_id"]
            isOneToOne: false
            referencedRelation: "staff"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tickets_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "staff"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tickets_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customer_overview"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tickets_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      treatments: {
        Row: {
          duration_minutes: number
          id: number
          is_active: boolean
          name: string
          price: number
          sort_order: number
        }
        Insert: {
          duration_minutes: number
          id?: never
          is_active?: boolean
          name: string
          price: number
          sort_order?: number
        }
        Update: {
          duration_minutes?: number
          id?: never
          is_active?: boolean
          name?: string
          price?: number
          sort_order?: number
        }
        Relationships: []
      }
    }
    Views: {
      customer_overview: {
        Row: {
          created_at: string | null
          created_by: string | null
          email: string | null
          full_name: string | null
          id: string | null
          marketing_consent: boolean | null
          next_appointment_at: string | null
          next_treatment: string | null
          notes: string | null
          open_tickets: number | null
          phone: string | null
          source: Database["public"]["Enums"]["customer_source"] | null
          updated_at: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "staff"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      activity_display_value: {
        Args: { p_field: string; p_value: string }
        Returns: string
      }
      agent_create_ticket: {
        Args: {
          p_description: string
          p_name: string
          p_phone: string
          p_request_type?: string
        }
        Returns: Json
      }
      agent_next_appointment: { Args: { p_phone: string }; Returns: Json }
      agent_report_incident: {
        Args: {
          p_details?: Json
          p_message: string
          p_node: string
          p_source: string
        }
        Returns: Json
      }
      can_write: { Args: never; Returns: boolean }
      current_staff_role: {
        Args: never
        Returns: Database["public"]["Enums"]["staff_role"]
      }
      dashboard_stats: { Args: never; Returns: Json }
      is_active_staff: { Args: never; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      normalize_phone: { Args: { p: string }; Returns: string }
    }
    Enums: {
      appointment_status: "scheduled" | "completed" | "cancelled"
      cancel_reason: "customer" | "clinic" | "no_show"
      customer_source:
        | "instagram"
        | "facebook"
        | "website"
        | "referral"
        | "whatsapp"
        | "ai_agent"
        | "other"
      staff_role: "admin" | "staff" | "viewer"
      ticket_priority: "normal" | "urgent"
      ticket_source:
        | "phone"
        | "whatsapp"
        | "instagram"
        | "facebook"
        | "website"
        | "walk_in"
        | "ai_agent"
      ticket_status: "new" | "in_progress" | "closed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof (PublicSchema["Tables"] & PublicSchema["Views"])> =
  (PublicSchema["Tables"] & PublicSchema["Views"])[T] extends { Row: infer R } ? R : never

export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]
